### ISSUE TITLE
AFK page not working

### ISSUE THREAD

**Issue by RihardKeegi** [Heliactyl/Heliactyl-11#26]

**Comment by RihardKeegi** [comment]
Heliactyl is on latest version

**Comment by pl3xed** [comment]
It means ur proxy is incorrectly configured
Halex runs 11.4.1 and it works fine
This will now be closed

**Comment by RihardKeegi** [comment]
how tf is my proxy incorrectly configured

**Comment by pl3xed** [comment]
U need to have the afkwspath shit configured

**Comment by RihardKeegi** [comment]
"arcio": {	
      "_comment": "You can make an arc.io widget on https://arc.io. You can get money using arc.io.",	
      "enabled": true,	
      "widgetid": "#S9WNdXwz",	
      "afk page": {	
        "_comment": "This will not effect any current arc.io sessions, and will require a restart to kick everyone out of the websocket sesison.",	
        "_comment2": "Make sure coins are enabled if you choose to enable this option!",	
        "enabled": true,	
        "_comment3": "If you change the path, you need to restart for it to take full effect.",	
        "path": "/arc-sw.js",	
        "_comment4": "This afk page will give the users [coins variable] coins every [every variable] seconds.",	
        "every": 60,	
        "_comment5": "The coins variable is meant to not be under 1. There may be bugs if the coins variable is less than 1.",	
        "coins": 1
      }

**Comment by manouelispro** [comment]
why did you change path it should be afkwspath

**Comment by RihardKeegi** [comment]
"arcio": {	
      "_comment": "You can make an arc.io widget on https://arc.io. You can get money using arc.io.",	
      "enabled": true,	
      "widgetid": "#S9WNdXwz",	
      "afk page": {	
        "_comment": "This will not effect any current arc.io sessions, and will require a restart to kick everyone out of the websocket sesison.",	
        "_comment2": "Make sure coins are enabled if you choose to enable this option!",	
        "enabled": true,	
        "_comment3": "If you change the path, you need to restart for it to take full effect.",	
        "path": "afkwspath",	
        "_comment4": "This afk page will give the users [coins variable] coins every [every variable] seconds.",	
        "every": 60,	
        "_comment5": "The coins variable is meant to not be under 1. There may be bugs if the coins variable is less than 1.",	
        "coins": 1
      }	
    }
  }
}

**Comment by RihardKeegi** [comment]
changed it back, still doesnt work

**Comment by manouelispro** [comment]
sent me your nginx conf

**Comment by RihardKeegi** [comment]
server {
        server_name client.rhinonodes.com;                                                                                                                         >        access_log /var/log/nginx/reverse-access.log;
        error_log /var/log/nginx/reverse-error.log;
        location / {
                    proxy_pass http://178.63.93.238:6001;                                                                                                          >
  }

    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/client.rhinonodes.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/client.rhinonodes.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
 server {
    if ($host = client.rhinonodes.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


        server_name client.rhinonodes.com;                                                                                                                         >        listen 80;
        listen [::]:80;
    return 404; # managed by Certbot


}

server {
    location = /arc-sw.js {
        proxy_pass https://arc.io;
        proxy_ssl_server_name on;
    }
}

**Comment by manouelispro** [comment]
heh thats a bad one

**Comment by manouelispro** [comment]
use this one

**Comment by manouelispro** [comment]
its on readme

**Comment by RihardKeegi** [comment]
it nows shows 502

**Comment by RihardKeegi** [comment]
server {
listen 80;
server_name client.rhinonodes.com;
return 301 https://$host$request_uri;
}
server {
listen 443;
server_name client.rhinonodes.com;
ssl_certificate /etc/letsencrypt/live/client.rhinonodes.com/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/client.rhinonodes.com/privkey.pem;
ssl on;
ssl_session_cache builtin:1000 shared:SSL:10m;
ssl_protocols SSLv3 TLSv1 TLSv1.1 TLSv1.2;
ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
ssl_prefer_server_ciphers on;
access_log /var/log/nginx/access.log;
location /afkwspath {
  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "upgrade";
  proxy_pass "http://localhost:6001/afkwspath";
}
location / {
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_pass http://localhost:6001;
proxy_read_timeout 90;
  }
}
