### ISSUE TITLE
Domain

### ISSUE THREAD

**Issue by TheGamer3514** [Heliactyl/Heliactyl-11#29]
I Am Trying To Setup Domain And It Is Not Working, Pls Help. Attached Is The Issue I Get When Trying To Go To It
![image](https://user-images.githubusercontent.com/79448904/152677628-38711d95-a4f9-4b18-b4e2-bc2869cb8928.png)

**Comment by RihardKeegi** [comment]
Its a problem with your reverse proxy/heliactyl is not running

**Comment by TheGamer3514** [comment]
i followed all the steps though
