### ISSUE TITLE
OAuth error

### ISSUE THREAD

**Issue by QuintenQVD0** [Heliactyl/Heliactyl-11#39]
This happens when i try to create a account. I can go to the dashboard , I can pres login , it redirect me to OAuth. I press accept and the page never go furder and i get this error in the terminal

https://paste.gg/p/anonymous/b1abb2d6f18e4162b89799d1cdbfb028

**Comment by Fabatax** [comment]
This has actually happened to me before, just make a new Applicatoin API key and give all read & write permissions

**Comment by QuintenQVD0** [comment]
thx it works
