### ISSUE TITLE
This line of code breaks the afk page. 

### ISSUE THREAD

**Issue by vachanmn123** [Heliactyl/Heliactyl-11#9]
https://github.com/Heliactyl/Heliactyl-11/blob/620fc0bc9e03a81c2e9ae6e335ed635a35ed1d7a/themes/default/coins.ejs#L25

**Comment by Vamp6969** [comment]
My PR was taken in and the AFK Page was fixed 😁

**Comment by manouelispro** [comment]
bruh badsk you idiot why didnt you delete the old script of afk page
